### ISSUE TITLE
different shapes and angles

### ISSUE THREAD

**Issue by biswajitSM** [BodenmillerGroup/napari-roi#3]
hi, Thanks for this very useful plugin; exactly the functionalities i was looking for - editing roi names, selecting between layer <-> table, and saving.

I was wondering if you have any plans to include other shapes (i.e. lines) and angle information in future.

i am getting familiar with your code structures to see if there is a convenient way to have/add these features.

**Comment by jwindhager** [comment]
Hi @biswajitSM, thanks for checking in - glad you find it useful!

Note that you can already "use" other shapes (e.g. circles, lines). What napari-roi saves are actually not the shapes themselves, but rectangular bounding boxes aligned to napari's coordinate system.

As for supporting other shapes (or rectangles not aligned to napari's coordinate system): here, the problem becomes data representation on disk. Currently, only X/Y/width/height are saved. For arbitrary shapes, one would need to find another data representation (e.g. store each point of the shape), which would make the plugin less useful for the most common use cases. That's why I didn't plan to add support for other shapes anytime soon myself.

However, I'm very open to discussing how one could implement support for arbitrary shapes and would be very happy to take pull requests. Unfortunately, the source code isn't documented well, but here are some notes that should help you getting started:
- `ROIWidget` is the central widget, holding a `ROITableModel`
- `ROITableModel` accesses shape data through the `ROILayerAccessor`/`ItemAccessor` classes
- `ROILayerAccessor` provides a list-like interface to a `Shapes` layer, exposing individual shapes as `ItemAccessor` instances
- Both `ROILayerAccessor.ItemAccessor` and `ROI` inherit from `ROIBase` - the `ROI` dataclass is primarily used for loading data
- Furthermore, `ROIWidget` publicly exposes the ROI data as mutable sequence using the `MutableItemModelSequenceWrapper` class, which notifies the `ROITableModel` of changes to the data

**Comment by biswajitSM** [comment]
Hi @jwindhager, thanks a lot for the tips.

The rectangular ROI is already very helpful and I can get my job done for now. One more piece of information that could be saved is the angle of the ROI. I am particularly interested in the line ROI which could be [X,Y,length,angle] or [x1,y1,x2,y2].

For me, probably the easier way (as I am not super fluent in python yet) to do it would be to replace the [X,Y,width,height] with [x1,y1,x2,y2] in your module into a separate plugin and adapt the data to napari's format. 

The module is very readable and well structured. So even though it's not well documented, I think I can adapt to my requirements.

thanks a lot again!
